dist: bionic
language: node_js
sudo: false
node_js:
  - '10'
before_install:
  - npm install -g grunt-cli
install: npm install

notifications:
  email:
    recipients:
      - gustavor@loymark.com
    on_success: always # default: change= never
    on_failure: always # default: always